### ISSUE TITLE
Incorrect get-SFschedule output details

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#11]
* Version 1.2.1.1

Here's what I get with the corresponding API method against v8 API:

```
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Week"
      },
      "hasError": false,
      "hours": 12,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 0,
      "monthdays": [],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 3,
      "scheduleInfo": {
        "name": "",
        "retention": "24:0:00",
        "volumeID": 197
      },
      "scheduleName": "WeekendSnap",
      "scheduleType": "Snapshot",
      "startingDate": null,
      "toBeDeleted": false,
      "weekdays": [
        {
          "day": 0,
          "offset": 1
        },
        {
          "day": 6,
          "offset": 1
        }
      ]
    }
  }
}
```

I'd expect to get similar info with `get-SFschedule`, but I can't (`-verbose` doesn't help).
Specifically `ScheduleInfo` is what I'm after but other details are missing as well.

```
PS C:\Program Files\SolidFire> get-sfschedule 3


Attributes       : {frequency}
HasError         : False
Hours            : 12
LastRunStatus    : Success
LastRunTimeStart :
Minutes          : 0
Monthdays        : {}
Paused           : False
Recurring        : True
RunNextInterval  : False
ScheduleID       : 3
ScheduleInfo     : SolidFire.Element.Api.ScheduleInfo
ScheduleName     : WeekendSnap
ScheduleType     : Snapshot
StartingDate     :
ToBeDeleted      : False
Weekdays         : {SolidFire.Element.Api.Weekday, SolidFire.Element.Api.Weekday}
```

**Comment by ahaid** [comment]
Hello @scaleoutsean,

The ScheduleInfo you're looking for is in the ScheduleInfo property of the return object. You can view the API requests and responses by setting $SFLogRequests and $SFLogResponses session variables to $true. Here is an example of setting those, calling for a schedule, and looking into the ScheduleInfo property.

```
PS C:\powershell> $SFLogRequests = $true
PS C:\powershell> $SFLogResponses = $true
PS C:\powershell>
PS C:\powershell>
PS C:\powershell> $sched = Get-SFSchedule
Request: {"id":3,"method":"ListSchedules","params":{}}
Response: {"id":3,"result":{"schedules":[{"attributes":{"frequency":"Time Interval"},"hasError":true,"hours":72,"lastRunStatus":"Failure","lastRunTimeStarted":"2016-11-16T00:00:00Z","minutes":0,"monthdays":[],"paused":false,"recurring":true,"runNextInterval":false,"scheduleID":1,"scheduleInfo":{"volumeID":"1"},"scheduleName":"AdamsSchedule","scheduleType":"Snapshot","startingDate":null,"toBeDeleted":false,"weekdays":[]}]}}
PS C:\powershell>
PS C:\powershell>
PS C:\powershell> $sched

Attributes       : {frequency}
HasError         : True
Hours            : 72
LastRunStatus    : Failure
LastRunTimeStart :
Minutes          : 0
Monthdays        : {}
Paused           : False
Recurring        : True
RunNextInterval  : False
ScheduleID       : 1
ScheduleInfo     : SolidFire.Element.Api.ScheduleInfo
ScheduleName     : AdamsSchedule
ScheduleType     : Snapshot
StartingDate     :
ToBeDeleted      : False
Weekdays         : {}



PS C:\powershell>
PS C:\powershell>
PS C:\powershell> $sched.ScheduleInfo


VolumeID                : 1
Volumes                 :
Name                    :
EnableRemoteReplication :
Retention               :
```

The Get-SFSchedule CmedLet is being re-worked for our next release (v1.3) and will have a different make-up. The implementation in 1.2.1.1 is tied exactly to the structure of the API response and is uncharacteristically difficult to manage. For v1.3 we changed it to be more object-oriented. It will match the [Schedule examples in the v1.1 SDK](https://github.com/solidfire/sdk-dotnet/blob/gh-pages/examples/snapshot-scheduling.md) which is what we're using going forward.

Additionally, we have taken a note to make use of the -Verbose flag instead of asking users to set $SFLogRequests and $SFLogResponses in the v1.3 version of PowerShell.

HTH,
Adam

**Comment by scaleoutsean** [comment]
Thanks Adam, that solves my question.
(I again made a mistake of consulting only the SF API doc and not looking into PS and the module docs - I did the same in the incorrectly filled #7... Sigh.)
By the way used with filters similar to what can be done in other commands, it makes it very easy to view and set snapshot schedules for many volumes at once. This is especially convenient when there are multiple schedules per volume, and many volumes (e.g. 3 \* 500). That's why I was looking into this and indeed a more convenient way to do that would be awesome.
