### ISSUE TITLE
Output redirection for VERBOSE: REQUEST

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#17]
* Ubuntu 16.04 client with PS 6 alpha 15 + SF PS Tools 1.3.0.124 + Element OS 8.6 API endpoint 
* Also on Windows 10 with the same release 1.3.0.124

I'm not sure if this is how PS works, but `-verbose *> file` only saves VERBOSE "log", not all verbose output (such as`VERBOSE: REQUEST` and `VERBOSE: RESPONSE` rows).

I tried different approaches to redirection and couldn't find a way to capture other details. 
This isn't something important, but in case those extra details are supposed to be output with output redirection or seems potentially useful, it'd be good to have it.

**Comment by ahaid** [comment]
Usage the -Verbose parameter is a bit misleading on this module. Because of some under-the-hood wiring, it's not actually writing these messages to the Verbose channel. It's just writing them to the console. That's also why you're unable to find these messages in the verbose log. I have removed the word "VERBOSE" from the `VERBOSE: REQUEST` and `VERBOSE: RESPONSE` messages in the latest hotfix (which hasn't been released publicly just yet). 

You can also enable these messages to be written to the screen using the `$SFLogRequests = $true` and `$SFLogResponses = $true` session variables. The -Verbose flag is just a quick way to turn them on for the duration of a single CmdLet.

I have recorded a new task in the backlog to implement -Verbose handling into the verbose channel but it won't come out in the 1.3 version of this module. It's more likely to be in the 1.4 version.
