### ISSUE TITLE
Test-SFPing returns as 'passed' even against IP's not on the network or part of the cluster

### ISSUE THREAD

**Issue by ddansf** [solidfire/PowerShell#72]
Test-SFPing returns as 'passed' even against IP's not on the network or part of the cluster.

To test:

Connect-SFCluster <MVIP> -VersionAPI <version> -Host
Test-SFPing -Hosts <host ip in cluster> (passes)
Test-SFPing -Hosts <ip not in the cluster> (passes)

Output Examples:

PS C:\Program Files\SolidFire> Test-SFPing -Hosts 10.117.34.133 (node is in cluster)

Result Duration        Details
------ --------        -------
Passed 00:00:00.000680 {10.117.34.133}

PS C:\Program Files\SolidFire> Test-SFPing -Hosts 10.117.34.199 (no host is on the network with this IP)

Result Duration        Details
------ --------        -------
Passed 00:00:02.500875 {10.117.34.199}

The operation appears to time out internally in 2.5 seconds, but instead of returning as failed, it returns as passed.

Tested with API versions 8.0, 9.0, and 10.0 on a 10.x cluster -- same result.

Also, when specifying multiple ping attempts, the false positive is returned very quickly (more quickly than is possible if that many attempts were actually made).

**Comment by ntavendale** [comment]
The result you see is the result of the API call. Even if the Ping fails, the api call still succeeds as the ping operation was performed and the ping result obtained.
Have changed cmdlet to present the result of the ping operation instead of the api call. This change will be in next release.
You can verify it works in the next version by using address 240.0.0.0 which is a reserved IP and not usually routable.
